language: java
jdk:
- oraclejdk7
- openjdk6
- oraclejdk8
branches:
  except:
  - www
cache:
  apt: true
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
- sudo apt-get -q update
- sudo apt-get -q install --no-install-recommends pandoc python-pandas
- pip install --user pandocfilters
- git fetch --depth=10000 origin
install: ./gradlew ciPrep
script: ./gradlew ciBuild
after_success:
- ./gradlew ciPublish
env:
  global:
  - TERM=dumb
  # DEPLOY_USER
  - secure: "QUz7X25DVKDZic9H2gGOvsCREtSYPxz01eQgCrGOmq1Ad0z1xMq7BvppvqL4mSOqnGG3OW5zddNf1qn/dJAc6hP78ZwSqeKBXo8cuQzA/PsFb0OlKG+kCVM9b+lQQShCexDxsg5DVbnrewDwDOtSYvxbrnhgN0IjRUoHp92778A="
  # DEPLOY_PASSWORD
  - secure: "GbHF/yVGEmktYE6OLLdSoM5FQjwrVNhAPNQNhiu60Mrcs8e1v3DXR3oOTg0FIvIxW9u5fjh4HlnGJbZirDV+7DSgN0dRofzIc4DS3ciwtl+24ro8D/yBBNKROJqG73gv7nNH5MIcJXhSqtpzjt8STshPskDOqy1qsMpwbycxEVw="
  - SITE_UPLOAD_URL=http://dev.grouplens.org/cgi/lenskit/site_upload.py
  # UPLOAD_SECRET
  - secure: O3DZVMifyBuguxnoLHG9YiWyJd6tOjAXdT8Mve27iw3fT1T3yZ2Jfx/9RPYlvEfOYVXbpeEkR/aDb1d+4RiipF/77/1RIRl1Rh9c+sjsJPosc1zwJImHzeUBMFBBYzfI3X58qB7q0oRanUcA5bIBi9B7t+krybQZUWp9QEgnTIw=
