language: java
jdk:
  - oraclejdk7
  - openjdk6
before_install:
  - sudo apt-get update
  - sudo apt-get install r-base-dev graphviz texlive-latex-base
install: sudo Rscript etc/setup-R-deps.R
script:
  - mvn install -Dgrouplens.mldata.acknowledge=yes
  - ./etc/ci/test-archetypes.sh

branches:
  except:
    - stable
