language: java
jdk:
  - oraclejdk7
  - openjdk6
before_install:
  - echo | sudo apt-add-repository ppa:marutter/rrutter
  - sudo apt-get update
  - sudo apt-get install r-cran-ggplot2 graphviz texlive-latex-base
install: true
script: mvn install -Ptest-archetypes -Dgrouplens.mldata.acknowledge=yes

branches:
  except:
    - stable
