language: java
jdk:
- oraclejdk7
- openjdk6
before_install:
- sudo apt-get update
- sudo apt-get install r-base-dev graphviz texlive-latex-base
- sudo Rscript etc/setup-R-deps.R
install: mvn dependency:go-offline
script:
- ./etc/ci/in-fold.sh build mvn install
- ./etc/ci/test-archetypes.sh
after_success:
- ./etc/ci/maybe-deploy.sh
- ./etc/ci/maybe-site.sh
- ./etc/ci/disk-stats.sh
branches:
  except:
  - stable
env:
  global:
  - secure: D3tCdALkjsp9W1hs1A32FaIOB0VkGT6+dG8maFY+In7wAF2KQ/jkYkYG+uutPn01gjaZgQiaGzal+Ck97+kfHMnm4YrK41mCL6XbZy3O7x68e/VK0GUVOJf88L8/bH2OhS33KA9Bif73I1eBy4ZfuQhXeh/UXqh7zOyOnYV1sJQ=
  - secure: IhWXB3LGdaEoiD7lgdaH83aVw/yK4T/f2lNalQn8skdA4nsLA1IWNgXU9MOFPTg50699oNiZOd39SptX5guZ25K0ov4nYXxPm1qCS6YpganfzeSiZ3sRZgBXKeTOnfzh8damVsDvebHYRMdPnjb1mELaoasNCHSfzprXL+PZois=
  - secure: JNscsfVaNUdOeSSi/PqSx8P5JxXlQA3m8nB4OxX1o5WZas9guG95Fzx/w5cycJVVsrxP3EhYFq4U9m9G1KbKorwvf+aO/C7rikhUTtYqm/Wl3xvZFelO5N14zCyjgMAdPScRdZ0JT6SzbKhei7/5hTkL4XDZlJ7rVZktAVynYYo=
